apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
  annotations:
    prometheus.io/port: "8088"
    prometheus.io/jvm: "true"
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: jmx-metrics
      port: 8088
      protocol: TCP