apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: datacubepy
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access":"proxy",
          "editable": true,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
    #      "url": "http://prometheus-service.monitoring.svc:8080",
          "url": "http://my-prometheus.datacubepy.svc:31000",
    #      "url": "http://localhost:9090",
          "version": 1
        }
      ]
    }