apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: datacubepy
  labels:
    type: local
spec:
  storageClassName: usersharebronze
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
