apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: debezium/kafka
        ports:
        - containerPort: 9093
          name: kafka
        command: [ "/bin/sh" ]
        args: [ "-c", "BROKER_ID=${POD_NAME##*-} KAFKA_ADVERTISED_LISTENERS=INTERNAL://$(POD_NAME).kafka.default.svc:9092 /docker-entrypoint.sh start" ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZOOKEEPER_CONNECT
          value: 'zookeeper.default.svc:2181'
        - name: KAFKA_LISTENERS
          value: 'INTERNAL://:9092'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'INTERNAL'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'INTERNAL:PLAINTEXT'